### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by fstamour**
- [x] fill-paragraphs in readme.org
- [x] The last sentence in readme.org is not finished, what were you going to write?

I didn't review yet...

### CODE REVIEW

**Comment by aartaka** [comment]
I had no fill column because of heavy Gemini influence, but I'm not hard-set on having no fill column. Let's have it.

README last sentence is fixed in 06feaf57fb2a9adf3d68b92a1333a56fdb02af10. Merging this PR, then?

**Comment by fstamour** [comment]
All good

**Comment by aartaka** [comment]
Merged as 7f6e9a28ccb59b66c24f5ba40b0b782b7adf06dc, thanks!

**Comment by fstamour** [comment]
> Thanks
No problem
This is obviously my best contribution to mankind xD

**Pull request merged**
